/*
**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
2. Create a task vLedTask() which will toggle the given LED
with given rate. LED number and rate will be given as argument.
In main() create four real-time tasks to operate four LEDs.**/

#include <stdlib.h>
#include<string.h>
#include <stdint.h>
#include <stdio.h>
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int rate;

void vLedTask1(void *pvParam)
{
	int led =*((int *)pvParam);
	while(1)
	{
		// work
		led_toggle(led);
		vTaskDelay(rate / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}


int main(int argc,char *argv[])
{
	if(argc<3){
		printf("enter 3 args: led no. and rate\n");
		return -1;
	}
	led_init(LED_RED);
	led_init(LED_GREEN);
	led_init(LED_BLUE);
	led_init(LED_ORANGE);

	int led=atoi(argv[1]);
	rate=atoi(argv[2]);
	if(led==14){
	xTaskCreate(vLedTask1, "task1-APeriodic", configMINIMAL_STACK_SIZE, (void *)&led, 1, NULL);
	}
	else if(led==15){
	xTaskCreate(vLedTask1, "2-APeriodic", configMINIMAL_STACK_SIZE,(void *)&led, 1, NULL);
	}
	else if(led==13){
	xTaskCreate(vLedTask1, "3-APeriodic", configMINIMAL_STACK_SIZE,(void *)&led, 1, NULL);
	}
	else if(led==14){
	xTaskCreate(vLedTask1, "4-APeriodic", configMINIMAL_STACK_SIZE, (void *)&led, 1, NULL);
	}
	vTaskStartScheduler();
	while(1);
	return 0;
}








